# Generated by Django 6.0.1 on 2026-01-11 23:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=200)),
                ('fichier', models.FileField(upload_to='backups/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('taille', models.CharField(blank=True, max_length=20)),
                ('reussi', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mot', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=256)),
                ('icon', models.CharField(default='fas fa-book', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('avatar', models.CharField(blank=True, max_length=10, null=True)),
                ('depuis', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('description', models.TextField(blank=True, max_length=256)),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encadreurs', to='core.track')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('memoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='core.track')),
            ],
            options={
                'ordering': ['-date_consultation'],
            },
        ),
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('auteur', models.CharField(max_length=100)),
                ('annee', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('fichier_pdf', models.FileField(upload_to='memoires/pdf/')),
                ('taille_fichier', models.CharField(blank=True, max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('mots_cles', models.ManyToManyField(blank=True, to='core.keyword')),
                ('encadreur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires_encadres', to='core.supervisor')),
                ('filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memoires', to='core.track')),
            ],
            options={
                'verbose_name': 'Mémoire',
                'verbose_name_plural': 'Mémoires',
                'ordering': ['-annee', 'titre'],
            },
        ),
    ]
