# Generated by Django 6.0.1 on 2026-01-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memories',
            old_name='fichier_pdf',
            new_name='fichier',
        ),
        migrations.RenameField(
            model_name='memories',
            old_name='mots_cles',
            new_name='motsCles',
        ),
        migrations.RenameField(
            model_name='memories',
            old_name='taille_fichier',
            new_name='taille',
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
