# Generated by Django 6.0.1 on 2026-01-12 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_fichier_pdf_memories_fichier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='encadreur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_memories', to='core.supervisor'),
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
