# Generated by Django 6.0.1 on 2026-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_memories_encadreur_alter_track_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='upload_fichier',
            field=models.FileField(null=True, upload_to='memoires/pdf/'),
        ),
        migrations.AlterField(
            model_name='memories',
            name='fichier',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
