# Generated by Django 6.0.1 on 2026-01-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_memories_upload_fichier_alter_memories_fichier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memories',
            old_name='upload_fichier',
            new_name='fichier_pdf',
        ),
    ]
