# Generated by Django 6.0.1 on 2026-01-12 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_upload_fichier_memories_fichier_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memories',
            old_name='taille',
            new_name='taille_fichier',
        ),
    ]
