# Generated by Django 6.0.1 on 2026-01-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_taille_memories_taille_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='fichier_pdf',
            field=models.FileField(null=True, upload_to='pdf/'),
        ),
    ]
