# Generated by Django 6.0.1 on 2026-01-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_memories_fichier_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='fichier_pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
